id: I45E1FC0E
legacy_id: P004560
ocr_import_info:
  bdrc_scan_id: W1KG3977
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:16:28'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:19:46.229309+00:00'
last_modified: 2022-08-31 23:20:00.661174
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3977
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3977
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རིག་འཛིན་བདེ་གཤེགས་འདུས་པ་ལས༔་རབ་ཏུ་གནས་པའི་ཆོ་ག་རྟེན་འབྲེལ་སྙིང་པོ་སོགས་ཆོས་ཚན་ཁག་ཅིག
  author: དྲི་མེད་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.522780793891722
  ocr_word_median_confidence_index: 0.5099999904632568
quality: null
bases:
  I1KG4162:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4162
      total_pages: 534
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4162.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.522780793891722
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
