id: I45E1FC0E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:19:49+00:00'
last_modified: '2022-06-08T01:56:34.929490+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3977
  title: རིག་འཛིན་བདེ་གཤེགས་འདུས་པ་ལས༔་རབ་ཏུ་གནས་པའི་ཆོ་ག་རྟེན་འབྲེལ་སྙིང་པོ་སོགས་ཆོས་ཚན་ཁག་ཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1C14:
      image_group_id: I1KG4162
      title: ''
      total_pages: 534
      order: 1
      base_file: 1C14.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
