id: opecha:P004560
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3977
  title: རིག་འཛིན་བདེ་གཤེགས་འདུས་པ་ལས༔་རབ་ཏུ་གནས་པའི་ཆོ་ག་རྟེན་འབྲེལ་སྙིང་པོ་སོགས་ཆོས་ཚན་ཁག་ཅིག
  volume: ''
  author: ''
