id: P004560
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:41:44.368871
source_metadata:
  id: bdr:W1KG3977
  title: རིག་འཛིན་བདེ་གཤེགས་འདུས་པ་ལས༔་རབ་ཏུ་གནས་པའི་ཆོ་ག་རྟེན་འབྲེལ་སྙིང་པོ་སོགས་ཆོས་ཚན་ཁག་ཅིག
  author: ''
  volumes:
    8b1789d115e04ca485eaa60b5273fd0e:
      image_group_id: I1KG4162
      title: ''
      volume_number: 1
      total_pages: 534
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
